export enum SettingKey {
  // Cấu hình chung
  TITLE = "TITLE",
  WEBSITE_DOMAIN = "WEBSITE_DOMAIN",
  LOGO_URL = "LOGO_URL",
  MAINTENANCE = "MAINTENANCE",

  // cấu hình website
  USE_MENU_CATEGORY = "USE_MENU_CATEGORY",
  ADMIN_MENU = "ADMIN_MENU",
  EDITOR_MENU = "EDITOR_MENU",
  MENU_CATEGORIES = "MENU_CATEGORIES",

  // game setting
  EARTH_REFETCH_TIME = "EARTH_REFETCH_TIME",
  FAN_REFETCH_TIME = "FAN_REFETCH_TIME",
  COOLING_INCREASE_UPGRADE = "COOLING_INCREASE_UPGRADE",
  CAPACITY_INCREASE_UPGRADE = "CAPACITY_INCREASE_UPGRADE",
  REGENERATION_INCREASE_UPGRADE = "REGENERATION_INCREASE_UPGRADE",
  START_DATE_SWAP_PERIOD = "START_DATE_SWAP_PERIOD",
  CONVERSION_RATE_ONE_MILEAGE_TO_TOKEN_PENDING = "CONVERSION_RATE_ONE_MILEAGE_TO_TOKEN_PENDING",
}
