import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ThemeModeScript,
  Navbar,
  NavbarBrand,
  NavbarCollapse,
  NavbarLink,
  NavbarToggle,
} from "flowbite-react";

import "../styles/index.scss";
import ContextProvider from "../providers";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FanSwap",
  description: "Generated by FanSwap",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <ContextProvider>
          <MainMenu />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}

const MainMenu = () => {
  return (
    <Navbar fluid className="">
      <NavbarBrand href="https://flowbite-react.com">
        <img
          src="/favicon.svg"
          className="mr-3 h-6 sm:h-6"
          alt="Flowbite React Logo"
        />
        <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
          FanSwap
        </span>
      </NavbarBrand>
      <div className="flex md:order-2">
        <ConnectWallet />
        <NavbarToggle />
      </div>
      <NavbarCollapse>
        <NavbarLink href="#" active>
          Trade
        </NavbarLink>
        <NavbarLink href="#">Bridge</NavbarLink>
        <NavbarLink href="#">Earn</NavbarLink>
        <NavbarLink href="#">Play</NavbarLink>
        <NavbarLink href="#">Faqs</NavbarLink>
        <NavbarLink href="#">Contact</NavbarLink>
      </NavbarCollapse>
    </Navbar>
  );
};

const ConnectWallet = () => {
  return <ConnectButton />;
};
